spring.application.name=backend
# Configuración de la Base de Datos
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/taller_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Configuración de JPA / Hibernate (El traductor mágico)
# "update" crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola las consultas SQL que hace Java (muy útil para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ===============================
# CONFIGURACIÓN DEL SERVIDOR DE CORREOS (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:gabrielisidro8@gmail.com}
spring.mail.password=${MAIL_PASSWORD:gpfodtmkljreylud}

# Propiedades de seguridad obligatorias de Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# CONFIGURACIÓN DE SEGURIDAD (JWT)
# ===============================
jwt.secret=${JWT_SECRET:TuTallerSaaS!ClaveSuperSeguraYSecretaParaFirmarTokens2026}
jwt.expiration=${JWT_EXPIRATION:36000000}